---
title: "PSTAT 174 FINAL PROJECT"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

# load packages
library(lubridate)
library(MASS)
library(dplyr) 
library(forecast)
library(qpcR)

```


```{r data_prep}
# Load the data
data = read.csv("city_temperature.csv")
# Select city Houston, Date, Temp
d1 = data[data$City=="Houston",]
data1 = data.frame(Month=d1$Month, Year=d1$Year, Temp = d1$AvgTemperature)
# Check missing values
sum(data1$Temp == -99)
# replace them with NA
for (i in (1:length(data1$Temp))){
  if ( data1$Temp[i]== -99){
    data1$Temp[i]= NA
  }
  if (nchar(as.character(data1$Month[i]))==1){
    data1$Month[i]=paste0("0",as.character(data1$Month[i]))
  }
}
sum(data1$Temp == -99)
sum(is.na(data1))
# Change to monthly average ignoring the NAs
data_houston=data1 %>%
  mutate(Date = as.Date(paste0(as.character(data1$Year),
                               as.character(data1$Month),"01"), "%Y%m%d"))%>%
  group_by(Date)%>%
  summarise(Avg=mean(Temp,na.rm =TRUE))
```

```{r train_test_sep}
# train/test seperation
train=data_houston[data_houston$Date<"2019-06-01",]
test=data_houston[data_houston$Date>="2019-06-01",][1:12,]

```

```{r ts_plot}
# Plot the original data
a= ts(data_houston$Avg, start = c(1995,1),frequency = 12)
temperature= ts(train$Avg, start = c(1995,1), end = c(2019,5),frequency = 12)
ts.plot(temperature, main = "Figure 3.1")
plot(decompose(temperature), sub = "Figure 3.1")
# Plot the original ACF PACF
par(mfrow=c(1,2))
acf(temperature,main = "Figure 3.2")
pacf(temperature,main = "Figure 3.3")
par(mfrow=c(1,1))
```

```{r trans}
# Boxcox transformation
t = 1:length(temperature)
fit = lm(temperature ~ t)
bcTransform = boxcox(temperature ~ t,plotit = TRUE)
lambda = bcTransform$x[which(bcTransform$y == max(bcTransform$y))]
temperature.bc = (1/lambda)*(temperature^lambda-1)
ts.plot(temperature.bc, main = "Figure 4.1")


```

```{r diff}
# Difference at 12
diff12=diff(temperature,12)
ts.plot(diff12, main = "Figure 4.2")
abline(h=0)
# Difference at 1
diff121=diff(diff12,1)
ts.plot(diff121, main = "Figure 4.3")
abline(h=0)
var(diff12)
var(diff121)
```

```{r model_identify}
# Plot new ACF PACF
acf(diff12,lag.max = 80, main = "Figure 5.1")
pacf(diff12,lag.max = 80, main = "Figure 5.2")

```

#d:0 D:1
#P:0
#Q:1,2
#p:1
#q:1,2,4

```{r modeling1}
# modeling
arima(temperature, order=c(1,0,1), seasonal = list(order = c(0,1,1), period = 12), method="ML")
AICc(arima(temperature, order=c(1,0,1), seasonal = list(order = c(0,1,1), period = 12), method="ML"))

arima(temperature, order=c(1,0,1), seasonal = list(order = c(0,1,2), period = 12), method="ML")
AICc(arima(temperature, order=c(1,0,1), seasonal = list(order = c(0,1,2), period = 12), method="ML"))

arima(temperature, order=c(1,0,2), seasonal = list(order = c(0,1,1), period = 12), method="ML")
AICc(arima(temperature, order=c(1,0,2), seasonal = list(order = c(0,1,1), period = 12), method="ML"))

arima(temperature, order=c(1,0,2), seasonal = list(order = c(0,1,2), period = 12), method="ML")
AICc(arima(temperature, order=c(1,0,2), seasonal = list(order = c(0,1,2), period = 12), method="ML"))

arima(temperature, order=c(1,0,4), seasonal = list(order = c(0,1,1), period = 12), method="ML")
AICc(arima(temperature, order=c(1,0,4), seasonal = list(order = c(0,1,1), period = 12), method="ML"))

arima(temperature, order=c(1,0,4), seasonal = list(order = c(0,1,2), period = 12), method="ML")
AICc(arima(temperature, order=c(1,0,4), seasonal = list(order = c(0,1,2), period = 12), method="ML"))

```

```{r modeling2}
# fixing some of the values 0
arima(temperature, order=c(1,0,1), seasonal = list(order = c(0,1,2), period = 12), fixed = c(NA,NA,NA,0),method="ML")
AICc(arima(temperature, order=c(1,0,1), seasonal = list(order = c(0,1,2), period = 12), fixed = c(NA,NA,NA,0), method="ML"))

arima(temperature, order=c(1,0,2), seasonal = list(order = c(0,1,1), period = 12), fixed = c(NA,NA,0,NA), method="ML")
AICc(arima(temperature, order=c(1,0,2), seasonal = list(order = c(0,1,1), period = 12), fixed = c(NA,NA,0,NA), method="ML"))

arima(temperature, order=c(1,0,2), seasonal = list(order = c(0,1,2), period = 12), fixed = c(NA,NA,0,NA,0), method="ML")
AICc(arima(temperature, order=c(1,0,2), seasonal = list(order = c(0,1,2), period = 12), fixed = c(NA,NA,0,NA,0), method="ML"))

arima(temperature, order=c(1,0,4), seasonal = list(order = c(0,1,1), period = 12), fixed = c(0,0,0,0,0,NA), method="ML",transform.pars = FALSE)
AICc(arima(temperature, order=c(1,0,4), seasonal = list(order = c(0,1,1), period = 12), fixed = c(0,0,0,0,0,NA), method="ML",transform.pars = FALSE))

arima(temperature, order=c(1,0,4), seasonal = list(order = c(0,1,2), period = 12), fixed = c(0,0,0,0,0,NA,0), method="ML",transform.pars = FALSES)
AICc(arima(temperature, order=c(1,0,4), seasonal = list(order = c(0,1,2), period = 12), fixed = c(0,0,0,0,0,NA,0), method="ML",transform.pars = FALSE))

```
lowest aicc
arima(temperature, order=c(1,0,1), seasonal = list(order = c(0,1,1), period = 12), method="ML")
AICc(arima(temperature, order=c(1,0,1), seasonal = list(order = c(0,1,1), period = 12), method="ML"))
    
```{r diagnostic fit}
# diagnostic testing 
fit1= arima(temperature, order=c(1,0,1), seasonal = list(order = c(0,1,1), period = 12), method="ML")

res <- residuals(fit1)
mean(res); var(res)
# Plot res
par(mfrow=c(1, 1))
ts.plot(res, main="Figure 6.1")
t <- 1:length(res)
fit.res = lm(res~ t)
abline(fit.res)
abline(h = mean(res), col = "red")
# plot acf pacf of res
par(mfrow=c(1, 2))
acf(res, main="Figure 6.2")
pacf(res, main="Figure 6.3")
# independency  test
l=round(sqrt(nrow(train)))
Box.test(res, lag = l, type = c("Box-Pierce"), fitdf = 4)
Box.test(res, lag = l, type = c("Ljung-Box"), fitdf = 4)
Box.test(res^2, lag = l, type = c("Ljung-Box"), fitdf = 0)
# normal test
shapiro.test(res)

par(mfrow=c(1,2))
hist(res,main = "Figure 6.4")
qqnorm(res)
qqline(res,col ="blue",main = "Figure 6.5")
ar(res, aic =TRUE, order.max = NULL, method = "yule-walker")
```
    
```{r diagnostic 2}
# diagnostic testing2 
fit1= arima(temperature, order=c(1,0,4), seasonal = list(order = c(0,1,1), period = 12), fixed = c(0,0,0,0,0,NA), method="ML",transform.pars = FALSE)

res <- residuals(fit1)
mean(res); var(res)
# Plot res
par(mfrow=c(1, 1))
ts.plot(res, main="Figure 6.1")
t <- 1:length(res)
fit.res = lm(res~ t)
abline(fit.res)
abline(h = mean(res), col = "red")
# plot acf pacf of res
par(mfrow=c(1, 2))
acf(res, main="Figure 6.2")
pacf(res, main="Figure 6.3")
# independency  test
l=round(sqrt(nrow(train)))
Box.test(res, lag = l, type = c("Box-Pierce"), fitdf = 4)
Box.test(res, lag = l, type = c("Ljung-Box"), fitdf = 4)
Box.test(res^2, lag = l, type = c("Ljung-Box"), fitdf = 0)
# normal test
shapiro.test(res)

par(mfrow=c(1,2))
hist(res,main = "Figure 6.4")
qqnorm(res)
qqline(res,col ="blue",main = "Figure 6.5")
ar(res, aic =TRUE, order.max = NULL, method = "yule-walker")
```


```{r forcast}
# fit model
fit1= arima(temperature, order=c(1,0,1), seasonal = list(order = c(0,1,1), period = 12), method="ML")
# plot data
pred.tr <- predict(fit1, n.ahead = 12)
U.tr= pred.tr$pred + 2*pred.tr$se  
L.tr= pred.tr$pred - 2*pred.tr$se
ts.plot(c(temperature),main ="Figure 7.1")
lines((length(temperature)+1):(length(temperature)+12),c(U.tr), col="blue", lty="dashed")
lines((length(temperature)+1):(length(temperature)+12),c(L.tr), col="blue", lty="dashed")
points((length(temperature)+1):(length(temperature)+12), pred.tr$pred, col="red")
lines((length(temperature)+1):(length(temperature)+12),c(test$Avg), col="green")



ts.plot(c(temperature),main ="Figure 7.2" , xlim = c(250,310))
lines((length(temperature)+1):(length(temperature)+12),c(U.tr), col="blue", lty="dashed")
lines((length(temperature)+1):(length(temperature)+12),c(L.tr), col="blue", lty="dashed")
points((length(temperature)+1):(length(temperature)+12), pred.tr$pred, col="red")
lines((length(temperature)+1):(length(temperature)+12),c(test$Avg), col="green")

fit1
```
